spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ok
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: xiaoming
      password: 123

server:
  servlet:
    context-path: /uaa
  port: 5000
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka