server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1.0  # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411 # 指定了 Zipkin 服务器的地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service  #将以"/user-api/**"开头的Uriqq转发到服务名为user-service的服务

